n1 = int(input('Digite o primeiro valor: '))
n2 = int(input('Digite o segundo valor: '))
n3 = int(input('Terceiro valor: '))
print('O menor valor digitado foi {}'.format(min(n1, n2, n3)))
print('o maior valor digitado foi {}'.format(max(n1, n2, n3)))